### ISSUE TITLE
Speeding up forward pass of TriangleModel

### ISSUE THREAD

**Issue by mathnathan** [PhotoWolf/TriangleModel_PyTorch#4]
Looks like **lesions** is defined as an instance variable. That means, for one instance of TriangleModel, **lesions** will be the same for all forward calls. Given that, the 6 if-else clauses can be executed only once, either in the constructor or in some sort of _update\_lesion_ method that should be introduced to modify the lesions. 

Each if-else clause may introduce a new branch when computing on the CPU (depending on how smart the compiler is). Best to remove them if possible. Especially from expensive routines like the forward call.

https://github.com/PhotoWolf/TriangleModel_PyTorch/blob/c455372344da7e3aadb053580f3625a5c0f8f81c/model.py#L218-L247

**Comment by PhotoWolf** [comment]
During phase 1 of training, our lesioning configuration often differs from one forward pass to the next (the changes are made in the _Trainer_ routines). I also can't imagine these if-else blocks causing a significant amount of overhead.

**Comment by mathnathan** [comment]
Got it. From an object-oriented perspective, being an instance attribute, **lesions** "should" be modified through a public mutator method. That may also enhance the readability of the code. Do what works best for you though

**Comment by PhotoWolf** [comment]
Made the change (see `set_lesions` in `TraingleModel`).
