### ISSUE TITLE
Irrelevant if-else block

### ISSUE THREAD

**Issue by mathnathan** [PhotoWolf/TriangleModel_PyTorch#5]
This if-else clause is irrelevant because **s2s_lesion** is a binary variable. As a result, the expression within the block operates as the if-else clause. This is also true for the sem_gradient on lines 265-267. In principle, try to replace as many binary if-else blocks with mathematical operations that act as the if-else block. Particularly in expensive routines like the forward pass.

https://github.com/PhotoWolf/TriangleModel_PyTorch/blob/c455372344da7e3aadb053580f3625a5c0f8f81c/model.py#L254-L256

**Comment by mathnathan** [comment]
After looking at the other if-else blocks in this section, it seems that most of them are unnecessary. Removing them may increase readability and speed up training time.

**Comment by PhotoWolf** [comment]
This is no longer an issue as of the newest (read: ten minutes ago) version of the code. 

The purpose of these if-statements was to reduce unnecessary computation. Sure, you could remove `if p2p_lesion` and the model would perform identically, but we would then be making additional forward calls to self.cleanup that just get zeroed out. Phase 1 of training already takes long enough as is; no reason to make it even longer. 

Note: the multiplication by [p2p_lesion] in line 256 is an artifact of an earlier version of the code.
